name: lesson_7
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.2
  go_router: ^15.1.1
  firebase_app_check: ^0.3.2+5
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  toastification: ^3.0.2
  flutter_dotenv: ^5.0.2
  http: ^1.3.0
  intl: ^0.20.2
  firebase_database: ^11.3.5
  flutter_slidable: ^4.0.0
  google_places_flutter: ^2.1.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/lakbay-logo.png
    - lib/assets/images/google-logo.png
    - lib/assets/images/forgot-password.png
    - lib/assets/images/verification.png
    - lib/assets/images/foursquare.png
    - lib/assets/images/onboarding1.png
    - lib/assets/images/onboarding2.png
    - lib/assets/images/onboarding3.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.png"
