// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmvjwTDNfzjy-ZSHUAl40pzWNPztCp-w',
    appId: '1:1067559891225:web:79ae95b2f71a451f68d588',
    messagingSenderId: '1067559891225',
    projectId: 'lesson-7-a161f',
    authDomain: 'lesson-7-a161f.firebaseapp.com',
    storageBucket: 'lesson-7-a161f.firebasestorage.app',
    measurementId: 'G-RCFLFSEW2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwI3Eb9BF-Li4_epcKLjmyW-xLmwBdIaM',
    appId: '1:1067559891225:android:6a5cec73773a3f6f68d588',
    messagingSenderId: '1067559891225',
    projectId: 'lesson-7-a161f',
    storageBucket: 'lesson-7-a161f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtiuiK7r7g83DsvjKtiBhPkSgxcSdww3s',
    appId: '1:1067559891225:ios:3a9f3459d42a628268d588',
    messagingSenderId: '1067559891225',
    projectId: 'lesson-7-a161f',
    storageBucket: 'lesson-7-a161f.firebasestorage.app',
    iosBundleId: 'com.example.lesson7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtiuiK7r7g83DsvjKtiBhPkSgxcSdww3s',
    appId: '1:1067559891225:ios:3a9f3459d42a628268d588',
    messagingSenderId: '1067559891225',
    projectId: 'lesson-7-a161f',
    storageBucket: 'lesson-7-a161f.firebasestorage.app',
    iosBundleId: 'com.example.lesson7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKmvjwTDNfzjy-ZSHUAl40pzWNPztCp-w',
    appId: '1:1067559891225:web:f2f6aaca1b773f1268d588',
    messagingSenderId: '1067559891225',
    projectId: 'lesson-7-a161f',
    authDomain: 'lesson-7-a161f.firebaseapp.com',
    storageBucket: 'lesson-7-a161f.firebasestorage.app',
    measurementId: 'G-TG88W4X5DC',
  );
}
